In [156]:
import pandas as pd 
data_link = '/Users/user/Desktop/Business_intelligence_in_Python/ToyotaCorolla.csv'
toyota_df = pd.read_csv(data_link,encoding = 'unicode_escape')

In [157]:
toyota_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
Id                   1436 non-null int64
Model                1436 non-null object
Price                1436 non-null int64
Age_08_04            1436 non-null int64
Mfg_Month            1436 non-null int64
Mfg_Year             1436 non-null int64
KM                   1436 non-null int64
Fuel_Type            1436 non-null object
HP                   1436 non-null int64
Met_Color            1436 non-null int64
Color                1436 non-null object
Automatic            1436 non-null int64
CC                   1436 non-null int64
Doors                1436 non-null int64
Cylinders            1436 non-null int64
Gears                1436 non-null int64
Quarterly_Tax        1436 non-null int64
Weight               1436 non-null int64
Mfr_Guarantee        1436 non-null int64
BOVAG_Guarantee      1436 non-null int64
Guarantee_Period     1436 non-null int64
ABS                  1436 non-null int64
Airbag_1             1436 non-null int64
Airbag_2             1436 non-null int64
Airco                1436 non-null int64
Automatic_airco      1436 non-null int64
Boardcomputer        1436 non-null int64
CD_Player            1436 non-null int64
Central_Lock         1436 non-null int64
Powered_Windows      1436 non-null int64
Power_Steering       1436 non-null int64
Radio                1436 non-null int64
Mistlamps            1436 non-null int64
Sport_Model          1436 non-null int64
Backseat_Divider     1436 non-null int64
Metallic_Rim         1436 non-null int64
Radio_cassette       1436 non-null int64
Parking_Assistant    1436 non-null int64
Tow_Bar              1436 non-null int64
dtypes: int64(36), object(3)
memory usage: 437.6+ KB

In [158]:
toyota_df.describe()

,Id,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,HP,Met_Color,Automatic,CC,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
mean,721.555014,10730.824513,55.947075,5.548747,1999.625348,68533.259749,101.502089,0.674791,0.055710,1576.85585,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,416.476890,3626.964585,18.599988,3.354085,1.540722,37506.448872,14.981080,0.468616,0.229441,424.38677,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,1.000000,4350.000000,1.000000,1.000000,1998.000000,1.000000,69.000000,0.000000,0.000000,1300.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.750000,8450.000000,44.000000,3.000000,1998.000000,43000.000000,90.000000,0.000000,0.000000,1400.00000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,721.500000,9900.000000,61.000000,5.000000,1999.000000,63389.500000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1081.250000,11950.000000,70.000000,8.000000,2001.000000,87020.750000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,1442.000000,32500.000000,80.000000,12.000000,2004.000000,243000.000000,192.000000,1.000000,1.000000,16000.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [159]:
#Preprocess 
toyota_df.loc[toyota_df.Fuel_Type=='CNG','Fuel_Type_CNG']=1
toyota_df.loc[toyota_df.Fuel_Type_CNG.isnull(),'Fuel_Type_CNG']=0

toyota_df.loc[toyota_df.Fuel_Type=='Diesel','Fuel_Type_Diesel']=1
toyota_df.loc[toyota_df.Fuel_Type_Diesel.isnull(),'Fuel_Type_Diesel']=0

In [160]:
toyota_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 41 columns):
Id                   1436 non-null int64
Model                1436 non-null object
Price                1436 non-null int64
Age_08_04            1436 non-null int64
Mfg_Month            1436 non-null int64
Mfg_Year             1436 non-null int64
KM                   1436 non-null int64
Fuel_Type            1436 non-null object
HP                   1436 non-null int64
Met_Color            1436 non-null int64
Color                1436 non-null object
Automatic            1436 non-null int64
CC                   1436 non-null int64
Doors                1436 non-null int64
Cylinders            1436 non-null int64
Gears                1436 non-null int64
Quarterly_Tax        1436 non-null int64
Weight               1436 non-null int64
Mfr_Guarantee        1436 non-null int64
BOVAG_Guarantee      1436 non-null int64
Guarantee_Period     1436 non-null int64
ABS                  1436 non-null int64
Airbag_1             1436 non-null int64
Airbag_2             1436 non-null int64
Airco                1436 non-null int64
Automatic_airco      1436 non-null int64
Boardcomputer        1436 non-null int64
CD_Player            1436 non-null int64
Central_Lock         1436 non-null int64
Powered_Windows      1436 non-null int64
Power_Steering       1436 non-null int64
Radio                1436 non-null int64
Mistlamps            1436 non-null int64
Sport_Model          1436 non-null int64
Backseat_Divider     1436 non-null int64
Metallic_Rim         1436 non-null int64
Radio_cassette       1436 non-null int64
Parking_Assistant    1436 non-null int64
Tow_Bar              1436 non-null int64
Fuel_Type_CNG        1436 non-null float64
Fuel_Type_Diesel     1436 non-null float64
dtypes: float64(2), int64(36), object(3)
memory usage: 460.0+ KB

In [161]:
#partition data 
from sklearn.model_selection import train_test_split
X = toyota_df[['Age_08_04','KM','Fuel_Type_CNG','Fuel_Type_Diesel','HP','Automatic','Doors','Quarterly_Tax' ,'Mfr_Guarantee','Guarantee_Period', 
                  'Airco', 'Automatic_airco','CD_Player','Powered_Windows','Sport_Model','Tow_Bar']] # which is the predictors 
y = toyota_df[['Price']] #which is the target variables

In [162]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 16 columns):
Age_08_04           1436 non-null int64
KM                  1436 non-null int64
Fuel_Type_CNG       1436 non-null float64
Fuel_Type_Diesel    1436 non-null float64
HP                  1436 non-null int64
Automatic           1436 non-null int64
Doors               1436 non-null int64
Quarterly_Tax       1436 non-null int64
Mfr_Guarantee       1436 non-null int64
Guarantee_Period    1436 non-null int64
Airco               1436 non-null int64
Automatic_airco     1436 non-null int64
CD_Player           1436 non-null int64
Powered_Windows     1436 non-null int64
Sport_Model         1436 non-null int64
Tow_Bar             1436 non-null int64
dtypes: float64(2), int64(14)
memory usage: 179.6 KB

In [163]:
y.head()

   Price
0  13500
1  13750
2  13950
3  14950
4  13750

In [164]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X,y,train_size=0.4,random_state=12345)

In [165]:
X_train.head()

,Age_08_04,KM,Fuel_Type_CNG,Fuel_Type_Diesel,HP,Automatic,Doors,Quarterly_Tax,Mfr_Guarantee,Guarantee_Period,Airco,Automatic_airco,CD_Player,Powered_Windows,Sport_Model,Tow_Bar
147,13,19988,0.0,0.0,110,0,5,85,1,3,1,1,1,1,1,0
1032,60,28500,0.0,0.0,110,0,5,85,0,3,1,0,0,1,0,0
555,50,40400,0.0,0.0,97,0,5,85,1,3,0,0,0,1,0,1
784,61,75609,0.0,0.0,86,0,3,69,1,3,0,0,0,0,0,0
722,57,88480,0.0,0.0,110,0,3,69,1,3,1,0,0,0,1,0

In [166]:
#preprocess 
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train_scale=sc_X.fit_transform(X_train)
X_test_scale=sc_X.transform(X_test)

sc_y= StandardScaler()
y_train_scale = sc_y.fit_transform(y_train)
y_test_scale = sc_y.transform(y_test)

In [167]:
from sklearn.neural_network import MLPRegressor

In [168]:
model_mlp_1 = MLPRegressor(hidden_layer_sizes = 3, activation='relu',random_state = 12345, max_iter = 3000)

In [169]:
model_fit_1 = model_mlp_1.fit(X_train_scale,y_train_scale.ravel())

In [170]:
y_pred_1=model_fit.predict(X_test_scale)

In [171]:
y_pred_1

array([-7.36213694e-01,  5.23600086e-01,  4.74599721e-01, -6.51499468e-01,
        3.64069023e-01, -6.85550530e-01, -2.03223398e-01,  1.94874215e+00,
        6.65839003e-01, -5.92025928e-01, -2.31791396e-01,  7.71637675e-01,
       -5.48212495e-01, -1.58909554e-01,  2.65901673e-02,  6.71532892e-01,
       -6.06618910e-01,  3.13374263e+00, -3.28866828e-01,  1.17358927e+00,
        4.56368022e-02, -1.05208513e+00, -2.28907365e-01, -6.06450003e-01,
       -4.86054566e-01, -6.75832730e-01,  1.70946926e+00, -4.05572933e-01,
        9.44481090e-01,  1.08094748e+00, -3.31711610e-01, -5.03910869e-01,
       -4.96969152e-01,  1.07369825e+00,  2.82564878e+00,  1.04553866e-01,
       -8.20465562e-01, -2.36718946e-01, -8.85641332e-01, -4.39323186e-01,
       -2.30103650e-01, -4.59360129e-01, -4.82661898e-02,  4.56901917e+00,
       -2.45706801e-01, -5.46807386e-01,  2.69844995e-01, -8.42773044e-01,
        2.33795621e+00, -4.24977936e-01,  4.75711588e-01,  6.45466425e-01,
       -7.88184331e-01, -1.64224821e-01,  6.68796730e-01, -1.99528994e-01,
       -1.02056007e+00,  3.42655063e-01,  8.99598285e-01,  3.07227628e-01,
        1.08830459e+00, -1.67075516e-01, -6.93808443e-01,  1.17067795e+00,
        1.05047155e+00,  3.59657417e-01,  9.00452621e-01,  1.49633125e-01,
        1.97657175e+00, -8.92864315e-01, -4.93601560e-01, -2.74448937e-01,
       -1.00077242e+00,  3.20826493e-01, -2.94924138e-01, -2.04103483e-02,
       -8.67042081e-01, -1.95582631e-01, -5.34675923e-01, -7.89492600e-01,
        4.37102773e-01, -3.08982363e-01, -5.23221294e-01, -7.86169408e-01,
       -2.73622425e-01, -1.68372045e-01, -2.03641312e-01, -4.43392341e-01,
        2.61765859e+00, -5.90933063e-01,  2.26879460e+00, -2.89537894e-01,
       -1.01754047e+00,  1.45855730e+00,  7.32554170e-01, -5.91785629e-01,
        3.13169314e-01,  8.06762019e-01, -5.71308349e-01, -7.64021676e-01,
       -3.87654847e-01, -1.08156465e+00,  4.22896445e-01, -6.79200961e-01,
       -4.88828678e-01,  2.91853114e+00, -1.96753239e-01, -7.94086853e-01,
       -7.79328403e-01,  1.45393529e+00, -8.51411703e-01,  1.48642386e+00,
       -7.37773404e-01, -1.42025861e+00,  5.51273427e-01, -2.62992991e-01,
        3.86404413e-01,  5.84986376e-01, -7.38174616e-01, -6.30075847e-01,
        7.96847379e-01, -2.83603502e-01, -5.77864042e-01, -7.07336392e-01,
       -6.83405584e-01, -1.47282916e-01, -2.92768121e-01, -1.94093662e-01,
        6.70721869e-01,  8.36541995e-02, -4.43820741e-01, -7.70445132e-01,
       -5.37775463e-01, -5.54674785e-01,  2.23082312e+00, -5.95975257e-01,
       -2.36502296e-01, -4.92896195e-01, -2.65524490e-01, -1.00557119e+00,
       -5.65453103e-01,  8.50903145e-02,  7.06078311e-01, -7.54071214e-01,
       -5.64178778e-01, -3.04997585e-01,  2.31138548e-02, -4.01071936e-01,
       -4.44391847e-01, -7.12512689e-01, -1.58344986e-02, -1.05191082e+00,
        2.41044938e+00, -7.53325219e-01, -6.56532864e-01, -8.58738707e-02,
       -5.74047973e-01,  2.25809312e+00,  1.92721844e-01, -9.80068105e-01,
       -6.45786597e-01,  5.50286198e-01, -7.95769957e-01, -6.96975079e-01,
       -5.57309327e-01, -7.09436097e-01,  2.64883846e+00,  8.20753424e-02,
       -1.61604624e-01,  3.13603658e-01, -1.08459207e-01, -4.25914474e-01,
        8.51905956e-01, -4.21625496e-01, -5.49071780e-01, -6.73723228e-01,
        2.84408025e+00,  2.92237165e+00,  3.34827433e-01, -7.74702657e-01,
        2.93218434e-02,  2.39211275e+00, -7.81484611e-01, -3.36644400e-01,
       -7.03769622e-01, -4.27104296e-01,  3.87660793e-01, -1.06215160e+00,
       -1.96469559e-02, -1.18599431e+00,  3.14900365e+00, -3.51658161e-01,
       -6.94618206e-01, -5.45446991e-01, -5.99876005e-01, -7.96007812e-01,
       -1.35643096e+00, -7.85468741e-01, -5.50138520e-01, -4.15330870e-02,
       -2.97947424e-01,  1.56397871e+00, -2.15822354e-01, -6.03272994e-01,
       -4.14224830e-01, -4.97422477e-01, -4.34766101e-01, -5.93420443e-01,
        8.45185438e-01, -5.72929380e-01, -7.27890385e-01,  2.87473437e-01,
       -1.06399542e+00, -3.28863988e-01,  1.07792640e+00,  2.24020443e+00,
       -5.81166264e-01, -1.25119279e+00, -3.40805702e-02, -8.84067769e-01,
       -9.33436625e-02, -4.30447234e-01,  1.92911800e+00, -8.21409756e-01,
       -5.34566297e-01,  2.54884001e+00, -5.71932545e-01,  1.26570416e+00,
       -2.76068207e-01, -1.82680426e-01, -5.94162465e-01,  7.38614993e-01,
       -4.84593130e-02, -7.23825360e-01, -3.29455678e-01, -6.70356865e-02,
       -6.15889618e-01, -6.31114521e-01, -1.08235965e+00,  1.06195000e+00,
       -2.87150318e-01, -8.51626502e-01,  1.44608594e+00,  1.41169930e+00,
       -4.79178873e-01,  2.29415343e+00,  9.69743024e-01,  1.11867869e+00,
       -6.92566448e-01,  2.45799273e-01, -5.52548512e-01, -2.39865636e-01,
       -6.17416483e-01, -3.58140897e-01, -9.38619428e-01, -4.70961445e-01,
        8.02883732e-01, -4.68379073e-01,  3.73384494e-01,  1.11081108e-01,
        2.01291026e+00, -2.36200999e-01,  1.23177308e+00, -1.79529808e-01,
       -9.29827049e-01,  9.87627040e-01, -5.43502358e-01, -8.69877268e-01,
       -2.16427826e-01,  2.41005831e+00,  1.98423663e+00, -6.23861088e-01,
        2.23252048e+00,  2.17927751e+00,  3.44572670e+00, -1.03221492e-01,
       -1.06017638e-01, -3.79155471e-01,  3.27312458e-02, -6.83290584e-01,
        6.75687426e-01, -6.28001991e-01,  3.67490309e+00, -4.81060178e-01,
       -5.77641607e-01, -5.27591236e-01, -5.35575151e-01,  8.86651342e-01,
        2.79022249e+00,  8.94718400e-02, -2.16243156e-01, -4.70651139e-01,
       -3.45348527e-01, -3.66590481e-01, -1.07729421e+00, -4.35893685e-01,
        3.01368385e-01,  3.21464654e-01,  7.71663933e-01, -9.57865768e-02,
       -5.41779368e-01, -6.72381281e-01, -1.02127009e+00, -4.92604007e-01,
       -1.11534757e-01, -5.44367957e-01, -9.92644179e-02, -6.06210013e-01,
       -4.34329372e-01, -3.06051250e-01, -3.80642784e-01, -4.57284007e-01,
       -4.63458028e-01, -8.48606800e-01, -1.33403570e+00, -9.56639559e-01,
       -5.27960581e-01, -2.93987922e-01,  1.50621683e-01, -4.50020082e-01,
       -2.48133189e-01,  1.43027150e+00, -6.43104136e-01, -1.11349438e+00,
        1.78938981e+00, -1.18531142e+00, -2.12067847e-01, -6.85146623e-01,
       -4.40258947e-01, -6.30253887e-01, -6.46187702e-01,  2.03327509e-01,
       -1.02558470e-01, -3.70191220e-01, -2.42987305e-01,  1.35573100e-01,
        6.21837851e-01, -5.61016171e-01, -4.88260614e-01, -4.58429567e-02,
       -1.40408340e-01, -8.94446448e-01, -3.88796014e-01, -6.77135732e-01,
       -5.57345695e-01, -5.30593040e-01, -5.32549532e-01, -4.58550813e-01,
       -2.81328576e-01, -9.67629212e-01, -5.97994720e-01, -2.72844207e-01,
       -5.27312777e-01,  5.06253565e-02,  1.28995149e+00,  8.70517663e-01,
       -5.49062667e-01, -1.58242155e-01, -5.32148818e-01, -4.98706329e-01,
       -3.26900418e-01, -7.09202454e-01, -7.22291493e-01, -1.75497325e-01,
        1.43462704e+00,  7.69635616e-01, -1.02061510e-01, -7.34670352e-01,
       -8.14047743e-01, -4.80222356e-01, -7.13483572e-01,  1.94944888e+00,
       -1.46441348e-01,  5.63589419e-01, -5.87553685e-01,  1.39406997e+00,
       -2.46057172e-01,  1.38274070e+00, -5.67016381e-01, -1.09488419e-01,
       -6.00091773e-01, -5.92151528e-01, -5.41035698e-01, -5.03628991e-01,
       -2.10695845e-01, -2.16780500e-01, -6.72332607e-01, -6.78934081e-01,
       -2.29810975e-01, -9.12177325e-01, -2.65889509e-01, -3.30099873e-01,
       -2.65800937e-01, -6.64378865e-01, -5.13423576e-01, -8.26543321e-01,
        3.52231281e-01,  2.25311908e+00,  2.76089013e-01,  7.18307063e-01,
       -8.38370558e-01, -4.17974695e-01, -6.85361793e-01,  1.76698817e+00,
       -1.98186260e-01, -8.50884319e-01,  2.57071893e-01, -8.20178222e-01,
       -7.09701412e-01,  1.90153415e+00, -8.83252941e-01, -6.82000950e-01,
       -1.73675196e-01,  2.81895474e+00, -1.75586421e-01,  2.52752663e+00,
       -4.22686366e-01, -1.11076478e-01,  3.07902541e+00,  1.52081587e-01,
        1.21898286e+00, -3.49389012e-01,  3.48302974e+00, -2.51730470e-01,
       -5.93327007e-01,  1.73275700e+00, -2.09997213e-01, -1.63789026e+00,
        1.22694718e+00, -4.40312142e-01,  8.49904139e-01, -8.57936983e-01,
       -3.18988896e-01, -1.91296409e-01, -7.92187305e-01,  7.46703434e-01,
       -7.98762481e-01, -5.10242697e-01,  1.27946468e+00, -1.27734836e-01,
        1.93647533e+00, -1.86519216e+00, -5.27937175e-01, -3.07759254e-01,
        2.15699469e+00, -3.89265490e-01,  7.05671877e-03, -7.28285495e-01,
       -6.47363609e-01, -3.73056004e-01,  7.16733942e-01, -8.84245409e-01,
       -2.12392202e-01,  1.32326618e+00, -9.52829731e-01, -3.38180892e-01,
       -1.43751039e+00, -1.08991616e-01, -7.27556441e-01, -4.09325764e-01,
       -1.10966074e+00, -3.21712479e-01, -4.62897524e-01, -3.82865237e-01,
        1.00672892e+00,  2.78479212e-01, -9.26893758e-01, -2.70467284e-01,
       -2.19677045e-01,  2.61172121e+00, -7.33235502e-01, -8.04593201e-01,
       -1.05128267e+00, -8.98839432e-01, -8.26450630e-01,  6.65267202e-01,
       -3.72383451e-01, -1.72973931e-01, -5.54822733e-01,  3.73901920e+00,
        8.73798405e-01,  1.64796271e+00, -1.06631307e-02,  6.28965125e-01,
       -9.13774732e-01, -5.64691961e-01, -6.09213085e-01, -3.49260407e-01,
       -4.94442971e-01, -6.18420299e-01, -3.43396054e-01, -7.39180353e-01,
       -6.81028665e-02, -5.69632161e-01, -2.07930738e-01, -5.05029994e-01,
        1.69075764e+00,  3.21566752e-01, -7.22699157e-01, -1.69118687e-01,
        3.19813196e+00,  4.43895566e-01, -8.03681488e-02, -3.64796088e-01,
       -8.20171915e-01, -3.74508277e-01, -6.66086515e-01, -1.98297020e-01,
       -2.25886364e-01, -6.41559766e-01, -3.84947980e-01,  7.63074679e-01,
        3.59578349e-01, -6.85452637e-02, -7.11767330e-01, -6.92450270e-01,
       -2.76106353e-01, -3.60101315e-01,  1.27878755e+00,  6.31397629e-01,
       -4.57979125e-01,  1.31948629e+00,  6.56681436e-01, -6.09084427e-01,
       -1.26277714e-01, -9.01126376e-01, -2.92820515e-01,  9.57866940e-02,
       -6.12532900e-01,  1.46485730e+00, -1.03481895e+00, -8.70821210e-01,
       -5.16517839e-02, -4.70107888e-02, -5.87129078e-02, -7.59825964e-01,
        2.07922479e+00,  1.09978432e-01, -2.26878596e-01, -1.32290546e-02,
       -4.76101915e-01, -3.33362637e-01, -8.28185001e-01,  1.56582656e-01,
       -6.20523054e-01,  1.55749538e+00, -8.85248011e-01, -4.34121116e-01,
       -5.71878100e-01, -9.09744911e-02, -7.38544982e-01, -5.39712193e-01,
       -5.16635979e-01, -4.32024350e-01,  2.83661800e-01, -9.77861255e-01,
       -6.23993696e-01, -6.30895349e-01, -7.15204019e-01,  3.37570333e+00,
       -5.14247899e-01,  1.01587160e+00,  1.68342965e+00, -4.34712796e-01,
       -6.57532556e-01,  2.19309552e+00, -4.95217154e-01, -4.10957388e-01,
        2.67431162e+00, -6.81453160e-01, -1.63185916e-01, -4.13070592e-01,
       -2.14558070e-01, -6.35701727e-01, -9.28851893e-01, -2.95815843e-01,
       -3.56101565e-01,  1.81595777e+00,  2.05616118e+00,  2.02510789e+00,
       -7.88084564e-01, -3.05535292e-01,  9.14724039e-01, -9.42768846e-01,
        5.26216503e-01, -3.81356860e-01, -4.87901354e-01, -2.66002980e-01,
        9.67450467e-01, -5.61132967e-01, -3.02062217e-01,  2.59373656e+00,
        7.74151705e-01,  4.48369852e-01, -7.64254239e-01, -3.91171588e-01,
       -1.14756563e+00, -5.06096741e-01, -5.02126034e-01, -5.47694627e-01,
       -4.07673837e-01, -5.52375076e-01, -5.99258901e-01, -5.30038592e-01,
       -7.27694425e-01,  8.46738864e-01, -4.20364229e-01,  3.42774984e+00,
       -3.76600196e-01,  1.15768727e+00, -7.45173031e-01,  7.39316893e-01,
       -7.16192757e-01,  2.90579452e+00,  1.83282141e+00, -1.60550345e-01,
        9.95827944e-01,  2.64310622e+00, -2.47223548e-01, -2.06853847e-03,
       -8.09214360e-02, -6.54576863e-01, -6.11674200e-02, -4.50886211e-01,
       -3.47435422e-01,  1.13794697e+00, -7.07080159e-01, -8.65416767e-01,
        6.39206279e-01, -8.69837674e-01, -7.00502305e-01, -4.05725489e-01,
       -5.82224881e-01,  1.23756351e+00, -9.19560720e-01, -6.34053887e-01,
       -9.43832164e-02, -6.65686635e-01, -2.31650867e-01, -4.24424724e-01,
        2.82667365e+00, -6.03868810e-01, -3.69969816e-01, -2.81111905e-01,
        9.89376488e-02, -6.16195494e-01,  8.76806780e-01, -1.26153230e-01,
       -8.19834225e-01,  9.69344658e-01, -5.73428389e-01,  1.75388034e+00,
       -1.06437119e+00, -3.12533196e-01,  2.25516506e+00,  2.07257837e-02,
       -4.48569782e-01, -2.13867282e-01, -4.64820689e-01, -5.37956865e-01,
       -4.94491605e-01, -4.65580861e-01, -4.57130264e-01, -4.17035879e-01,
        3.50562557e+00,  2.66544531e+00,  1.26356679e+00, -1.20782655e-01,
       -8.96272924e-01, -4.02667701e-01, -8.04805171e-01,  8.43771923e-01,
       -5.87460713e-01, -1.10950950e-01, -2.00176513e-01,  8.33155442e-01,
       -4.94861881e-01, -1.41449713e-01, -3.81329679e-01,  1.37948098e+00,
       -3.42266490e-01,  4.38314583e+00, -3.77135277e-01,  4.84819451e-01,
        6.98376481e-01, -1.31308549e-01, -5.70724122e-01,  3.08776566e+00,
       -7.45119548e-01, -7.51773219e-01, -4.49289668e-01, -2.86038840e-01,
        5.23194413e-01, -3.30083547e-01, -3.90463995e-01, -7.58582792e-01,
       -5.07009861e-01, -5.54576827e-01,  5.17101171e-01, -6.46936861e-01,
       -9.59597076e-01, -6.70455779e-01,  2.88149043e-01,  1.26166340e-01,
       -7.15102378e-01, -8.00413402e-01,  1.43174078e+00,  2.91275606e-01,
       -1.91049609e-01, -3.80344232e-01,  6.50526119e-02, -7.57950750e-01,
        4.42470561e-02, -3.81090771e-01, -8.95015835e-01, -6.58348390e-01,
        4.74393887e-01, -4.95325009e-01, -1.17645908e+00, -5.70728968e-01,
        1.54841435e-02,  4.74761443e-01,  7.68626449e-01, -1.48760592e-01,
        2.63951167e+00,  2.99868425e-01,  2.78802535e+00, -2.83651440e-02,
        3.24188035e-03, -6.78190336e-01,  1.60509968e+00, -7.71232291e-01,
        1.02101425e-01, -3.77031922e-01,  3.29884849e-02, -2.42726243e-01,
       -4.73118475e-01, -7.27660685e-01,  2.93793943e+00,  1.89317001e-01,
       -5.83210421e-01, -3.95302868e-01, -4.21541699e-01, -5.89821095e-01,
        1.18382630e+00, -7.82738609e-01, -6.67132338e-02, -4.92000951e-01,
       -5.45066320e-01, -4.75400951e-01, -1.83397990e-01,  2.10479977e-01,
       -2.88787683e-01, -2.62785870e-01, -1.02851987e+00, -1.60312582e-01,
       -8.52490195e-01, -6.48669685e-01,  1.02798993e+00, -3.29423369e-01,
       -8.79331542e-02, -6.66527131e-01,  2.18628309e+00, -7.97320016e-03,
       -3.63747935e-02, -6.24508656e-01,  4.61386104e-02, -7.25880447e-01,
       -7.39146602e-02, -6.89718903e-01, -3.68701698e-01, -2.59972213e-01,
       -3.94173513e-01, -6.81043529e-01, -8.35658599e-01,  5.90029460e-01,
        1.43558067e-01, -3.51493839e-01, -3.75220092e-01, -4.45509191e-01,
       -4.26887274e-01,  2.98527055e-01, -8.77486271e-01, -7.91892959e-01,
        3.45634260e+00, -2.89301053e-01, -6.94027777e-01, -5.56244447e-01,
       -1.02323123e+00,  8.97052215e-01, -5.08736856e-01, -4.21535843e-01,
        1.29801261e+00, -6.76987924e-01, -5.43644868e-02, -2.45964623e-01,
        3.28295460e+00, -6.21656690e-01,  9.80739269e-01,  3.59021379e-01,
       -1.06721276e+00,  5.23216108e-01, -3.61459529e-01, -4.93412222e-01,
       -1.33057674e-01, -6.18067406e-01,  3.41379705e+00,  2.36279828e+00,
        1.94290848e+00, -4.37659121e-01,  2.01915652e+00, -1.02993560e-01,
        1.24447329e-01, -5.73907191e-01, -5.93923492e-01,  5.86237230e-01,
        1.06772995e-01, -7.21887725e-01,  5.10815450e-01, -9.48493331e-01,
       -7.33967541e-01, -5.72350293e-01, -1.02915983e+00,  3.06287415e-02,
        3.16792130e-01,  4.87488669e-01, -3.96920486e-01, -3.37161297e-01,
       -5.65593403e-01, -6.08757556e-01, -3.35227959e-01, -2.48011119e-01,
       -4.12701207e-01,  5.43048841e-01, -6.85435593e-01,  1.15467555e+00,
       -3.53029273e-01, -8.66860670e-01,  1.05140346e+00,  1.97435674e+00,
       -6.71989664e-01, -3.23367830e-01, -1.28663917e-01,  2.42368691e+00,
       -5.09992869e-03, -4.73439424e-01, -6.14439138e-01, -3.08855320e-01,
       -7.68512631e-01, -2.74285059e-01, -7.55707970e-01, -6.70089345e-01,
        1.10117941e+00, -4.25770383e-01,  4.40809716e-01,  1.50655106e-01,
       -8.81826775e-01, -3.75896393e-01, -5.92800008e-01,  1.11381627e+00,
        4.08026579e-01,  5.59973492e-01])

In [172]:
result_df = pd.DataFrame({'predict':y_pred_1,'actual':y_test_scale.ravel()})

In [173]:
result_df.head()

    predict    actual
0 -0.736214 -1.306155
1  0.523600  0.624698
2  0.474600 -0.326937
3 -0.651499 -0.809650
4  0.364069  0.348862

In [174]:
import numpy as np 
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import mean_absolute_error
 
MSE_1 = mean_squared_error(result_df[['actual']],result_df[['predict']])

print('MSE is ：',MSE)
print('RMSE is ：',np.sqrt(MSE))

MSE is ： 0.11873270580095498
RMSE is ： 0.3445761248272361

In [180]:
## neuralnetwork 2 
model_mlp_2 = MLPRegressor(hidden_layer_sizes = (5,5), activation='relu',random_state = 12345, max_iter = 3000)

In [181]:
model_fit_2 = model_mlp_2.fit(X_train_scale,y_train_scale.ravel())

In [185]:
y_pred_2 =model_fit_2.predict(X_test_scale)

In [186]:
result2_df = pd.DataFrame({'predict':y_pred_2,'actual':y_test_scale.ravel()})

In [187]:
result2_df.head()

    predict    actual
0 -0.880250 -1.306155
1  0.322091  0.624698
2 -0.146753 -0.326937
3 -0.257606 -0.809650
4  0.151215  0.348862

In [188]:
MSE_2 = mean_squared_error(result2_df[['actual']],result2_df[['predict']])

print('MSE is ：',MSE_2)
print('RMSE is ：',np.sqrt(MSE_2))

MSE is ： 0.1304737110567339
RMSE is ： 0.36121144923262594